# -*- coding: utf-8 -*-
"""DS-3-Modul-3-Amaliyot-tozalash.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ekEahXJ2vAYwqTLxsSk3j_zNtF33O77F

# ![Imgur](https://i.imgur.com/5pXzCIu.png)

# **DATA SCIENCE VA SUN'IY INTELLEKT PRAKTIKUM**

## 3.2 Ma'lumotlarni tayyorlash

# **AMALIYOT**
## Ma'lumotlarga ishlov berish
"""

import pandas as pd
import numpy as np

df = pd.read_csv("https://raw.githubusercontent.com/mukhammad-irmatov/health_dataset/main/healt_info.csv")
df.head(3)

"""Bu dataset sug'urta kompaniyasining real ma'lumotlardan tuzilgan. Bu datasetda 480000 qator sug'urta ma'lumotlar tashkil topgan.
Quyida datasetning ba'zi ustunlari haqida qisqacha ma'lumot

*   Sno = seriya raqami
*   AGE = yoshi
*   SEX = jinsi (female = ayol, male = erkak)
*   CASTE_NAME = kasta nomi (Hindistonda har bir inson ma'lum bir kastaga oid bo'ladi)
*   CATEGORY_CODE = kategoriya kodi
*   CATEGORY_Name = kategoriya nomi
*   SURGERY_CODE = operatsiya kodi
*   Mandal_Name = mandal nomlanishi ya'ni familiyasi desak ham bo'ladi
*   Mortality Y/N = vafot etgan yoki vafot etmaganligi
*   MORTALITY_DATE = qachon vafot etganligi

### **1-mashq**. Datasetdagi barcha takrorlangan qatorlar sonini toping
"""

# Javobni shuyerga yozing
df.duplicated().sum()

#@title **To'g'ri javob**
sum(df.duplicated())

"""#### **2-mashq**. Datasetdagi quyidagi ustunlar o'chirib yuborilsin:<br>
*   Sno
*   CATEGORY_CODE
*   SURGERY_CODE
*   MANDAL_NAME
*   DISTRICT_NAME
*   HOSP_DISTRICT
<BR>

"""

# Javobni shuyerga yozing
df.drop(["CATEGORY_CODE",
"SURGERY_CODE",
"MANDAL_NAME",
"DISTRICT_NAME"], axis=1, inplace=True)

"""#### **3-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni unique funksiyasi orqali tekshiring.



"""

# Javobni shuyerga yozing
df.SEX.unique()
# df.head()

#@title **To'g'ri javob**
df["SEX"].unique()

"""#### **4-mashq**. Datasetdagi sex(jinsi) nomli qatordagi qiymatlarni **Erkak** va **Ayol** ga o'zgartiring:
O'zgartirish quyidagicha bo'lsin:


*   Male -> Erkak
*   Male(child) -> Erkak
*   Female - > Ayol
*   Female(child) - Ayol
*   MALE -> Erkak
*   FEMALE -> Ayol




"""

# Javobni shuyerga yozing
dict = {"Male": "Erkak",
"Male(child)" : "Erkak",
"Female":"Ayol",
"Female(child)":"Ayol",
"MALE":"Erkak",
"FEMALE":"Ayol"}
df['SEX']=df['SEX'].map(dict)
df.head()

"""#### **5-mashq**. Endi xuddi shu SEX columndagi ma'lumotlarni raqamlarga o'zgartiring: Erkaklarni 1 raqamiga, Ayollarni 0 raqamiga o'zgartiring.
*   Erkak -> 1
*   Ayol -> 0
"""

# Javobni shuyerga yozing
df['SEX'] = df["SEX"].map({"Erkak":1,"Ayol":0})

"""#### **6-mashq**. Shu jarayonni HOSP_TYPE ustuni uchun ham amalga oshiring.
*   G - General hospital (umumiy kasalxona) degani
*   C - Special hospital (maxsus kasalxona) degani
<br><b>O'zgarish quyidagicha bo'lsin:</b>
*   G -> Umumiy
*   C -> Maxsus

"""

# Javobni shuyerga yozing
dict = {"G":"Umumiy", "C":"Maxsus"}
df['HOSP_TYPE'] = df["HOSP_TYPE"].map(dict)

df.head()

"""#### **7-mashq**. O'zgartirish amalga oshirilgach, HOSP_TYPE ustunida qancha Umumiy va qancha Maxsus kasalxonalar borligini ham aniqlang

"""

# Javobni shuyerga yozing
df["HOSP_TYPE"].value_counts()

"""#### **8-mashq**. Datasetda qancha takrorlangan qatorlar borligini aniqlang  

"""

# Javobni shuyerga yozing
df.duplicated().sum()

"""#### **9-mashq**. Datasetda barcha takrorlangan qatorlarni o'chirib yuboring  

"""

# Javobni shuyerga yozing
df.drop_duplicates(inplace=True)

"""#### **10-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning o'rtacha qiymatlarini toping.

"""

# Javobni shuyerga yozing
df.groupby('HOSP_TYPE').CLAIM_AMOUNT.mean()

"""#### **11-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), ClAIM_AMOUNTning minimum qiymatlarini toping.

"""

# Javobni shuyerga yozing
df.groupby("HOSP_TYPE").CLAIM_AMOUNT.min()

"""#### **12-mashq**. Datasetdan shifoxona turiga ko'ra (umumiy va maxsus), CLAIM_AMOUNTning maksimum qiymatlarini toping.

"""

# Javobni shuyerga yozing
df.groupby("HOSP_TYPE").CLAIM_AMOUNT.max()

""".agg() yordamida istalgan funksiyalarni chaqirishimiz mumkin, misol uchun numpy dagi mean (o'rta qiymat) funiksiyasini ham qo'shamiz. Natijalarni faqat price ustuni uchun chiqaramiz:

#### **13-mashq**. Datasetdan jinsiga ko'ra CLAIM_AMOUNTning min, max va o'rta qiymatlarni agg() usuli yordamida toping.
"""

# Javobni shuyerga yozing
df.groupby("SEX").CLAIM_AMOUNT.agg([min,max,np.mean])