# -*- coding: utf-8 -*-
"""cleaning_df.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sK7ESoa-jQXgGP0_-us1X2Et4yTwAV1W
"""

import pandas as pd
import numpy as np

df = pd.read_csv("https://github.com/jamshid-ds/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

pd.isna(df)

pd.isna(df).sum()

nulls = df.isnull().sum()
rows = df.shape[0]
(nulls/rows)*100

df2 = df.dropna()
df2.shape

df2

df.dropna(axis=1)

df.dropna(axis=1, thresh=48) # thresh - chegara berish

df.dropna(subset=['length','body-style']) # subset - ustunlarni tanlash

df.dropna(subset=['price'], inplace=True)

df = pd.read_csv("https://github.com/jamshid-ds/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

df.fillna(0)

df.fillna({'wheel-base':90, 'horsepower':100})

df[df.company=='audi']

df[df.company=='audi'].fillna(method='ffill')

df[df.company=='toyota']

df[df.company=='toyota'].fillna(method='bfill')

df[df.company=='toyota']=df[df.company=='toyota'].fillna(method='bfill')

df[df.company=='toyota']

dfh = df[df['body-style']=='hatchback']
dfh

dfh.fillna(dfh.mean())

df.fillna({'horsepower':np.mean(df['horsepower']), "wheel-base":np.mean(df['wheel-base'])})

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv')
df.head()

df.duplicated()

sum(df.duplicated())

df.shape

df.drop_duplicates()

df.drop_duplicates(['country'])

df.drop_duplicates(['country','rank'])

df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data_nan.csv", index_col=0)
df.head()

df['num-of-cylinders'].unique()

dict = {'two':2, 'three':3, 'four':4, 'five':5, 'six':6, 'eight':8, 'twelve':12}

df['cylinders'] = df['num-of-cylinders'].map(dict)

df[['num-of-cylinders','cylinders']]

kurs=10720 # 1$=10720 so'm
df['price'].map(lambda x: x*kurs)

df['price_uzs'] = df['price'].map(lambda x: x*kurs)
df.head()

df.head()

df.replace('four',4)

df.replace(['four','six'],[4,6])

df.replace({'four':4, 'six':6})

df2 = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', index_col='country')

df2.rename(index=str.upper, columns=str.upper) # Har doimngidek o'zgarishlarni saqlab qolish uchun inplace=True qilishingiz mumkin

df2.rename(index={'Macau':'MAKAO'}, columns={'pop2021':'population'})

df2.rename(columns=str.upper)

import pandas as pd
import numpy as np

df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

df.drop_duplicates(inplace=True)

df.sort_index(inplace=True)

bins = [0, 1000, 10000, 30000, 50000, 100000, 300000, 1500000]

population = df.pop2021

oraliq = pd.cut(population,bins)

oraliq

df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

range = pd.cut(df.price, bins)

range.value_counts()

range = pd.qcut(df.price, 3)
range.value_counts()

range = pd.cut(df.price, 3)
range.value_counts()

range = pd.qcut(df.horsepower, 3)
range.value_counts()

df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)
df.head()

df.groupby('company').mean()

df.groupby('company').price.max() #max narxlarni chiqaramiz

df.groupby(['company','body-style']).mean()

df.groupby(['company']).max()

df.groupby('company').agg([len, min, max]) #len - guruhdagi elementlar soni, min - guruh uchun minimum, max - guruh uchun maximum

df.groupby('body-style').price.agg([len, min, max, np.mean])

df.head()
df.shape

np.random.permutation(61)

df.index=np.random.permutation(len(df))
df

df.take(np.random.permutation(len(df)))

df.sample(10, replace=True)

